config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get 'test_answers/find', to:'test_answers#find'
  get 'test_answers/:id/save', to:'test_answers#save'
  get 'tests/:id/score', to:'tests#score'

  resources :question_answers

  resources :test_answers

  resources :questions

  resources :tests

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_scope :user do
    get 'users/post_status' , to: 'users/registrations#post_status',:as => "user_posts_status"
  end

end

app/models/test_answer.rb
# Instituto Tecnologico de Costa Rica
# Curso: Introduccion al desarrollo de aplicaciones para web
# IV Tarea Programada
# Ruby on Rails/ Bootstrap/ TDD y BDD
# Profesor: Erick Hernandez
# Estudiantes:
#     - Daniel Solis Mendez / 2013099996
#     - Melvin Elizondo Perez / 2013099997
# I Semestre 2015

class TestAnswer < ActiveRecord::Base
  belongs_to :test
  belongs_to :user
  has_many :question_answers,dependent: :destroy
end

app/controllers/test_answers_controller.rb
class TestAnswersController < ApplicationController
  before_action :set_test_answer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @test_answers = TestAnswer.all
    respond_with(@test_answers)
  end

  def show
    respond_with(@test_answer)
  end

  def new
    @test_answer = TestAnswer.new
    respond_with(@test_answer)
  end

  def edit
  end

  def create
    @test_answer = TestAnswer.new(test_answer_params)
    @test_answer.save
    render layout:false,text:@test_answer.id
  end

  def update
    @test_answer.update(test_answer_params)
    respond_with(@test_answer)
  end

  def destroy
    @test_answer.destroy
    respond_with(@test_answer)
  end


  def save
    # Array with user answers
    user_answers = params[:answers]

    cnt = 1
    user_answers.each do |user_answer|
      qa = QuestionAnswer.find_by( test_answer_id: params[:id],question_number:cnt)
      p qa
      if qa!=nil
        qa.update(choice:user_answer,test_answer_id:params[:id],question_number:cnt)
      else
        QuestionAnswer.create(choice:user_answer,test_answer_id:params[:id],question_number:cnt)
      end
      cnt += 1
    end
    flash[:success] = "Guardado correctamente a las " + Time.now.strftime("%d/%m/%y %I:%M:%S %P")
    render layout:false, text: 'Success'
  end




  def find
    ta = TestAnswer.find_by( test_id: params[:testID],user_id:params[:userID])
    test_id = 'no'
    if (ta != nil)
      test_id = ta.id
    end
    render layout: false, text: test_id
  end


  private
    def set_test_answer
      @test_answer = TestAnswer.find(params[:id])
    end

    def test_answer_params
      params.require(:test_answer).permit(:status, :test_id,:user_id,:score)
    end

end

app/helpers/test_answers_helper.rb
module TestAnswersHelper
end

app/views/test_answers/_form.html.haml
= form_for @test_answer do |f|
  - if @test_answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@test_answer.errors.count, "error")} prohibited this test_answer from being saved:"
      %ul
        - @test_answer.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/test_answers/edit.html.haml
%h1 Editing test_answer

= render 'form'

= link_to 'Show', @test_answer
\|
= link_to 'Back', test_answers_path

app/views/test_answers/index.html.haml
.row
  .col-lg-12
    %h1.page-header
      Examenes disponibles

    %table.table.table-striped.table-hover
      %thead
        %tr
          %th Nombre
          %th Descripcion
          %th Inicia
          %th Termina
          %th

      %tbody
        - @test_answers.each do |test|
          %tr
            %td= test.name
            %td= test.description
            %td= test.begins_at
            %td= test.ends_at
            - if user_signed_in?
              %td= link_to 'Hacer', test,class:"btn btn-default"
            - else
              %td
                %i Inicie Sesion para hacer

app/views/test_answers/new.html.haml
%h1 New test_answer

= render 'form'

= link_to 'Back', test_answers_path

app/views/test_answers/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_test_answer_path(@test_answer)
\|
= link_to 'Back', test_answers_path