config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get 'test_answers/find', to:'test_answers#find'
  get 'test_answers/:id/save', to:'test_answers#save'
  get 'tests/:id/score', to:'tests#score'

  resources :question_answers

  resources :test_answers

  resources :questions

  resources :tests

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_scope :user do
    get 'users/post_status' , to: 'users/registrations#post_status',:as => "user_posts_status"
  end

end

app/models/question_answer.rb
# Instituto Tecnologico de Costa Rica
# Curso: Introduccion al desarrollo de aplicaciones para web
# IV Tarea Programada
# Ruby on Rails/ Bootstrap/ TDD y BDD
# Profesor: Erick Hernandez
# Estudiantes:
#     - Daniel Solis Mendez / 2013099996
#     - Melvin Elizondo Perez / 2013099997
# I Semestre 2015

class QuestionAnswer < ActiveRecord::Base
  belongs_to :test_answer
end

app/controllers/question_answers_controller.rb
class QuestionAnswersController < ApplicationController
  before_action :set_question_answer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @question_answers = QuestionAnswer.all
    respond_with(@question_answers)
  end

  def show
    respond_with(@question_answer)
  end

  def new
    @question_answer = QuestionAnswer.new
    respond_with(@question_answer)
  end

  def edit
  end

  def create
    @question_answer = QuestionAnswer.new(question_answer_params)
    @question_answer.save
    respond_with(@question_answer)
  end

  def update
    @question_answer.update(question_answer_params)
    respond_with(@question_answer)
  end

  def destroy
    @question_answer.destroy
    respond_with(@question_answer)
  end

  private
    def set_question_answer
      @question_answer = QuestionAnswer.find(params[:id])
    end

    def question_answer_params
      params.require(:question_answer).permit(:choice,:test_answer_id,:question_number)
    end
end

app/helpers/question_answers_helper.rb
module QuestionAnswersHelper
end

app/views/question_answers/_form.html.haml
= form_for @question_answer do |f|
  - if @question_answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question_answer.errors.count, "error")} prohibited this question_answer from being saved:"
      %ul
        - @question_answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :choice
    = f.text_field :choice
  .actions
    = f.submit 'Save'

app/views/question_answers/edit.html.haml
%h1 Editing question_answer

= render 'form'

= link_to 'Show', @question_answer
\|
= link_to 'Back', question_answers_path

app/views/question_answers/index.html.haml
%h1 Listing question_answers

%table
  %thead
    %tr
      %th Choice
      %th
      %th
      %th

  %tbody
    - @question_answers.each do |question_answer|
      %tr
        %td= question_answer.choice
        %td= link_to 'Show', question_answer
        %td= link_to 'Edit', edit_question_answer_path(question_answer)
        %td= link_to 'Destroy', question_answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question answer', new_question_answer_path

app/views/question_answers/new.html.haml
%h1 New question_answer

= render 'form'

= link_to 'Back', question_answers_path

app/views/question_answers/show.html.haml
%p#notice= notice

%p
  %b Choice:
  = @question_answer.choice

= link_to 'Edit', edit_question_answer_path(@question_answer)
\|
= link_to 'Back', question_answers_path